spring.application.name=finance-control
spring.datasource.url=jdbc:mysql://localhost:3307/finance-control
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
